INSERT INTO `language_phrases` (`language_id`, `phrase`, `translated`) VALUES
(4, 'Log In', 'تسجيل الدخول'),
(4, 'Login', 'تسجيل الدخول'),
(4, 'See your growth and get consulting support!', 'انظر نموك واحصل على الدعم الاستشاري!'),
(4, 'Email', 'بريد إلكتروني'),
(4, 'Your Email', 'بريدك الإلكتروني'),
(4, 'Password', 'كلمة المرور'),
(4, 'Remember Me', 'تذكرنى'),
(4, 'Forget Password?', 'نسيان كلمة المرور؟'),
(4, 'Not have an account yet?', 'ليس لديك حساب بعد؟'),
(4, 'Create Account', 'إنشاء حساب'),
(4, 'Home', 'بيت'),
(4, 'Courses', 'دورات'),
(4, 'All Courses', 'جميع الدورات'),
(4, 'Bootcamp', 'Bootcamp'),
(4, 'Search...', 'يبحث...'),
(4, 'Search courses', 'دورات البحث'),
(4, 'Cart', 'عربة'),
(4, 'Sign Up', 'اشتراك'),
(4, 'Contact with Us', 'الاتصال معنا'),
(4, 'Top Categories', 'الفئات العليا'),
(4, 'Useful links', 'روابط مفيدة'),
(4, 'Course', 'دورة'),
(4, 'Blog', 'مدونة'),
(4, 'Company', 'شركة'),
(4, 'Phone : ', 'هاتف :'),
(4, 'Email : ', 'بريد إلكتروني :'),
(4, 'Email address', 'عنوان البريد الإلكتروني'),
(4, 'Submit', 'يُقدِّم'),
(4, 'About Us', 'معلومات عنا'),
(4, 'Privacy Policy', 'سياسة الخصوصية'),
(4, 'Terms And Use', 'الشروط والاستخدام'),
(4, 'Sales and Refunds', 'المبيعات واسترداد'),
(4, 'FAQ', 'التعليمات'),
(4, 'Close', 'يغلق'),
(4, 'Are you sure?', 'هل أنت متأكد؟'),
(4, 'You can''t bring it back!', 'لا يمكنك إعادته!'),
(4, 'Cancel', 'يلغي'),
(4, 'Yes, I''m sure', 'نعم ، أنا متأكد'),
(4, 'Just Now', 'الآن'),
(4, 'Success !', 'نجاح !'),
(4, 'Attention !', 'انتباه !'),
(4, 'An Error Occurred !', 'حدث خطأ!'),
(4, 'Remove from wishlist', 'إزالة من قائمة الأمنيات'),
(4, 'This course added to your wishlist', 'تمت إضافة هذه الدورة إلى قائمة الأمنيات الخاصة بك'),
(4, 'Add to wishlist', 'أضف إلى قائمة الرغبات'),
(4, 'This course removed from your wishlist', 'تمت إزالة هذه الدورة التدريبية من قائمة الأمنيات الخاصة بك'),
(4, 'Enter your keywords', 'أدخل كلماتك الرئيسية'),
(4, 'Show less', 'تظهر أقل'),
(4, 'Show more', 'تظهر المزيد'),
(4, 'Showing', 'تظهر'),
(4, 'of', 'ل'),
(4, 'data', 'بيانات'),
(4, 'Grid', 'شبكة'),
(4, 'List', 'قائمة'),
(4, 'Filter', 'فلتر'),
(4, 'Categories', 'فئات'),
(4, 'Price', 'سعر'),
(4, 'Paid', 'مدفوع'),
(4, 'Discount', 'تخفيض'),
(4, 'Free', 'حر'),
(4, 'Level', 'مستوى'),
(4, 'Beginner', 'مبتدئ'),
(4, 'Intermediate', 'متوسط'),
(4, 'Advanced', 'متقدم'),
(4, 'language', 'لغة'),
(4, 'English', 'إنجليزي'),
(4, 'Spanish', 'الأسبانية'),
(4, 'Italic', 'مائل'),
(4, 'German', 'الألمانية'),
(4, 'Ratings', 'تقييمات'),
(4, 'No data found !', 'لم يتم العثور على بيانات!'),
(4, 'Please attempt utilizing the suitable keywords in your search query to obtain more precise results.', 'يرجى محاولة استخدام الكلمات الرئيسية المناسبة في استعلام البحث الخاص بك للحصول على نتائج أكثر دقة.'),
(4, 'Back', 'خلف'),
(4, 'Dashboard', 'لوحة القيادة'),
(4, 'Number of Courses', 'عدد الدورات'),
(4, 'Number of Lessons', 'عدد الدروس'),
(4, 'Number of Enrollment', 'عدد التسجيل'),
(4, 'Number of Students', 'عدد الطلاب'),
(4, 'Number of Instructor', 'عدد المدرب'),
(4, 'Admin Revenue This Year', 'إيرادات المشرف هذا العام'),
(4, 'Admin Revenue', 'إيرادات المسؤول'),
(4, 'Course Status', 'حالة الدورة'),
(4, 'Explore Courses', 'استكشاف الدورات'),
(4, 'Active', 'نشيط'),
(4, 'Upcoming', 'قادم'),
(4, 'Pending', 'قيد الانتظار'),
(4, 'Private', 'خاص'),
(4, 'Draft', 'مسودة'),
(4, 'Inactive', 'غير نشط'),
(4, 'Pending Requested withdrawal', 'في انتظار السحب المطلوب'),
(4, 'Instructor Payout', 'تعويضات المدرب'),
(4, 'Main Menu', 'القائمة تشغيل'),
(4, 'Category', 'فئة'),
(4, 'Manage Courses', 'إدارة الدورات'),
(4, 'Add New Course', 'أضف دورة جديدة'),
(4, 'Coupons', 'كوبونات'),
(4, 'Manage Bootcamps', 'إدارة المعسكرات'),
(4, 'Add New Bootcamp', 'إضافة Bootcamp جديد'),
(4, 'Purchase History', 'سجل الشراء'),
(4, 'Student enrollment', 'تسجيل الطلاب'),
(4, 'Course enrollment', 'الالتحاق بالطبع'),
(4, 'Enrollment History', 'تاريخ الالتحاق'),
(4, 'Enroll student', 'تسجيل الطالب'),
(4, 'Payment Report', 'تقرير الدفع'),
(4, 'Offline payments', 'مدفوعات غير متصلة بالإنترنت'),
(4, 'Instructor Revenue', 'إيرادات المدرب'),
(4, 'Payment History', 'سجل الدفع'),
(4, 'Users', 'المستخدمون'),
(4, 'Admin', 'مسؤل'),
(4, 'Manage Admin', 'إدارة المشرف'),
(4, 'Add New Admin', 'أضف مسؤول جديد'),
(4, 'Instructor', 'مدرب'),
(4, 'Manage Instructors', 'إدارة المدربين'),
(4, 'Add new Instructor', 'أضف مدربًا جديدًا'),
(4, 'Instructor Setting', 'إعداد المدرب'),
(4, 'Application', 'طلب'),
(4, 'Student', 'طالب'),
(4, 'Manage Students', 'إدارة الطلاب'),
(4, 'Add new Student', 'أضف طالب جديد'),
(4, 'Message', 'رسالة'),
(4, 'Newsletter', 'النشرة الإخبارية'),
(4, 'Manage Newsletters', 'إدارة النشرات الإخبارية'),
(4, 'Subscribed User', 'المستخدم المشترك'),
(4, 'Contacts', 'جهات الاتصال'),
(4, 'Blogs', 'المدونات'),
(4, 'Manage Blogs', 'إدارة المدونات'),
(4, 'Pending Blogs', 'مدونات معلقة'),
(4, 'Settings', 'إعدادات'),
(4, 'System Settings', 'إعدادات النظام'),
(4, 'Website Settings', 'إعدادات الموقع'),
(4, 'Payment Settings', 'إعدادات الدفع'),
(4, 'Manage Language', 'إدارة اللغة'),
(4, 'Live Class Settings', 'إعدادات الفئة الحية'),
(4, 'SMTP Settings', 'إعدادات SMTP'),
(4, 'Certificate Settings', 'إعدادات الشهادة'),
(4, 'Player Settings', 'إعدادات اللاعب'),
(4, 'Open AI Settings', 'افتح إعدادات الذكاء الاصطناعي'),
(4, 'Home Page Builder', 'منشئ الصفحة الرئيسية'),
(4, 'SEO Settings', 'إعدادات SEO'),
(4, 'About', 'عن'),
(4, 'Manage Profile', 'إدارة الملف الشخصي'),
(4, 'Admin Panel', 'لوحة المسؤول'),
(4, 'View site', 'عرض الموقع'),
(4, 'AI Assistant', 'لديك مساعد'),
(4, 'Help Center', 'مركز المساعدة'),
(4, 'Read documentation', 'قراءة الوثائق'),
(4, 'Watch video tutorial', 'مشاهدة الفيديو التعليمي'),
(4, 'Get customer support', 'احصل على دعم العملاء'),
(4, 'Order customization', 'ترتيب تخصيص'),
(4, 'Request a new feature', 'طلب ميزة جديدة'),
(4, 'Get Services', 'الحصول على الخدمات'),
(4, 'My Profile', 'ملفي الشخصي'),
(4, 'Sign Out', 'تسجيل الخروج'),
(4, 'Confirm', 'يتأكد'),
(4, 'Loading', 'تحميل'),
(4, 'Website name', 'اسم الموقع'),
(4, 'Website title', 'عنوان الموقع'),
(4, 'Website keywords', 'الكلمات الرئيسية'),
(4, 'Website description', 'وصف الموقع'),
(4, 'Author', 'مؤلف'),
(4, 'Slogan', 'شعار'),
(4, 'System email', 'البريد الإلكتروني للنظام'),
(4, 'Address', 'عنوان'),
(4, 'Phone', 'هاتف'),
(4, 'Youtube API key', 'youtube API مفتاح'),
(4, 'Get YouTube API key', 'احصل على مفتاح واجهة برمجة تطبيقات YouTube'),
(4, 'If you want to use Google Drive video, you need to enable the Google Drive service in this API', 'إذا كنت ترغب في استخدام فيديو Google Drive ، فأنت بحاجة إلى تمكين خدمة Google Drive في واجهة برمجة التطبيقات هذه'),
(4, 'Vimeo API key', 'Vimeo API Key'),
(4, 'get Vimeo API key', 'احصل على مفتاح Vimeo API'),
(4, 'Purchase code', 'رمز الشراء'),
(4, 'System language', 'لغة النظام'),
(4, 'Course selling tax', 'دورة بيع المسار'),
(4, 'Enter 0 if you want to disable the tax option', 'أدخل 0 إذا كنت ترغب في تعطيل خيار الضرائب'),
(4, 'Device limitation', 'الحد من الجهاز'),
(4, 'Footer text', 'نص تذييل'),
(4, 'Footer link', 'رابط تذييل'),
(4, 'Save Changes', 'حفظ التغييرات'),
(4, 'Update Product', 'تحديث المنتج'),
(4, 'File', 'ملف'),
(4, 'Update', 'تحديث'),
(4, 'Version updated successfully', 'تم تحديث الإصدار بنجاح'),
(4, 'Select your service', 'حدد خدمتك'),
(4, 'Course title', 'عنوان المسار'),
(4, 'Course short description', 'وصف قصير'),
(4, 'Course long description', 'وصف طويل'),
(4, 'Course requirements', 'متطلبات الدورة'),
(4, 'Course outcomes', 'نتائج الدورة'),
(4, 'Course faq', 'أسئلة وأجوبة بالطبع'),
(4, 'Course seo tags', 'دورة SEO علامات'),
(4, 'Course lesson text', 'نص الدرس بالطبع'),
(4, 'Course certificate text', 'نص شهادة الدورة'),
(4, 'Course quiz text', 'نص مسابقة الدورة'),
(4, 'Course blog title', 'عنوان المدونة الدورة'),
(4, 'Course blog post', 'مدونة الدورة التدريبية'),
(4, 'Course thumbnail', 'Thumbnail بالطبع'),
(4, 'Enter your keyword', 'أدخل كلمتك الرئيسية'),
(4, 'Generate', 'يولد'),
(4, 'Generating', 'توليد'),
(4, 'Your images', 'صورك'),
(4, 'Generated text', 'نص تم إنشاؤه'),
(4, 'Copy', 'ينسخ'),
(4, 'Copied', 'نسخ'),
(4, 'Not found', 'لم يتم العثور عليها'),
(4, 'About This Application', 'حول هذا التطبيق'),
(4, 'Software version', 'إصدار البرنامج'),
(4, 'Laravel version', 'نسخة لارافيل'),
(4, 'Check update', 'تحقق من التحديث'),
(4, 'Php version', 'إصدار PHP'),
(4, 'Curl enable', 'تمكين حليقة'),
(4, 'enabled', 'تمكين'),
(4, 'Product license', 'ترخيص المنتج'),
(4, 'Enter valid purchase code', 'أدخل رمز الشراء صالح'),
(4, 'Customer support status', 'حالة دعم العملاء'),
(4, 'Support expiry date', 'دعم تاريخ انتهاء الصلاحية'),
(4, 'Customer name', 'اسم العميل'),
(4, 'Customer support', 'دعم العملاء'),
(4, 'Payment setting', 'إعداد الدفع'),
(4, 'Currency Settings', 'إعدادات العملة'),
(4, 'Heads up !!', 'انتباه !!'),
(4, 'Ensure that the system currency and all active payment gateway currencies are same', 'تأكد من أن عملة النظام وجميع عملات بوابة الدفع النشطة هي نفسها'),
(4, 'Select currency', 'حدد العملة'),
(4, 'Currency position', 'موقف العملة'),
(4, 'Left', 'غادر'),
(4, 'Right', 'يمين'),
(4, 'Left with a space', 'غادر بمساحة'),
(4, 'Right with a space', 'حق مع مساحة'),
(4, 'No', 'لا'),
(4, 'Yes', 'نعم'),
(4, 'Want to keep test mode enabled', 'تريد الحفاظ على تمكين وضع الاختبار'),
(4, 'sandbox client id', 'معرف عميل Sandbox'),
(4, 'sandbox secret key', 'مفتاح Sandbox السري'),
(4, 'production client id', 'معرف عميل الإنتاج'),
(4, 'production secret key', 'المفتاح السري للإنتاج'),
(4, 'setting', 'جلسة'),
(4, 'public key', 'المفتاح العام'),
(4, 'secret key', 'المفتاح السري'),
(4, 'public live key', 'المفتاح المباشر العام'),
(4, 'secret live key', 'مفتاح Live Secret'),
(4, 'Choose an option', 'اختر خيارًا'),
(4, 'bank information', 'معلومات البنك'),
(4, 'secret test key', 'مفتاح الاختبار السري'),
(4, 'public test key', 'مفتاح الاختبار العام'),
(4, 'Cookie Policy', 'سياسة ملفات تعريف الارتباط'),
(4, 'Accept', 'يقبل'),
(4, 'Learn More', 'يتعلم أكثر'),
(4, 'Students has Enrolled', 'التحق الطلاب'),
(4, 'Page Builder', 'باني الصفحة'),
(4, 'Create Page', 'إنشاء صفحة'),
(4, '#', '#'),
(4, 'Page Name', 'اسم الصفحة'),
(4, 'Status', 'حالة'),
(4, 'Action', 'فعل'),
(4, 'Edit Home Page', 'تحرير الصفحة الرئيسية'),
(4, 'Edit Home', 'تحرير المنزل'),
(4, 'Preview', 'معاينة'),
(4, 'Edit Layout', 'تحرير التصميم'),
(4, 'Edit Page', 'صفحة تحرير'),
(4, 'Edit', 'يحرر'),
(4, 'Delete', 'يمسح'),
(4, 'Home page activated', 'تم تنشيط الصفحة الرئيسية'),
(4, 'The Leader in online learning', 'الرائد في التعلم عبر الإنترنت'),
(4, 'Get Started', 'ابدأ'),
(4, 'Special Featured Course', 'دورة مميزة خاصة'),
(4, 'Those course highlights a handpicked course with exceptional content or exclusive offerings.', 'يسلط هذه المسار الضوء على دورة تم اختيارها بدقة مع محتوى استثنائي أو عروض حصرية.'),
(4, 'Why Choose Us', 'لماذا تختارنا'),
(4, 'Happy student', 'طالب سعيد'),
(4, 'Quality educators', 'المعلمين الجودة'),
(4, 'Premium courses', 'دورات مميزة'),
(4, 'Cost-free course', 'دورة خالية من التكلفة'),
(4, 'Top Rated Course', 'مسار أعلى تصنيف'),
(4, 'Top rated course showcases the highest-rated course based on student reviews and performance metrics.', 'تعرض الدورة التدريبية ذات التصنيف الأعلى أعلى درجات التصنيف بناءً على مراجعات الطلاب ومقاييس الأداء.'),
(4, 'What the people Thinks About Us', 'ماذا يفكر الناس فينا'),
(4, 'It highlights feedback and testimonials from users, reflecting their experiences and satisfaction.', 'يسلط الضوء على التعليقات والشهادات من المستخدمين ، مما يعكس تجاربهم ورضاهم.'),
(4, 'Frequently Asked Questions', 'الأسئلة المتداولة'),
(4, 'Our Latest Blog', 'آخر مدونة لدينا'),
(4, 'The latest blog highlights the most recent articles, updates, and insights from our platform.', 'تبرز آخر مدونة أحدث المقالات والتحديثات والرؤى من نظامنا الأساسي.'),
(4, 'Wishlist', 'قائمة أمنيات'),
(4, 'Log Out', 'تسجيل الخروج'),
(4, 'Logout', 'تسجيل الخروج'),
(4, 'Admin Dashboard', 'لوحة معلومات المشرف'),
(4, 'It is a long established fact that a reader will be the distract by the read content of a page layout', 'إنها حقيقة راسخة أن القارئ سيكون مشتتًا من خلال قراءة محتوى تخطيط الصفحة'),
(4, 'Subscribe to stay tuned for new web design and latest updates. Let''s do it!', 'اشترك في التزامنا لتصميم الويب الجديد وآخر التحديثات.دعونا نفعل ذلك!'),
(4, 'False', 'nan'),
(4, '404 not found', '404 لم يتم العثور عليها'),
(4, 'The page you requested could not be found', 'لا يمكن العثور على الصفحة التي طلبتها'),
(4, 'Please try the following', 'الرجاء تجربة ما يلي'),
(4, 'Check the spelling of the url', 'تحقق من تهجئة عنوان URL'),
(4, 'If you are still puzzled, click on the home link below', 'إذا كنت لا تزال في حيرة ، فانقر على رابط المنزل أدناه'),
(4, 'Back to home', 'العودة إلى المنزل'),
(4, 'Become An Instructor', 'كن مدرسًا'),
(4, 'Title', 'عنوان'),
(4, 'Description', 'وصف'),
(4, 'Video Url', 'عنوان URL فيديو'),
(4, 'Image', 'صورة'),
(4, 'Banner Information', 'معلومات لافتة'),
(4, 'Add new', 'أضف جديد'),
(4, 'Remove', 'يزيل'),
(4, 'Video Link', 'رابط الفيديو'),
(4, 'Youtube', 'يوتيوب'),
(4, 'HTML5', 'HTML9'),
(4, 'All Category', 'كل الفئة'),
(4, 'Add new category', 'أضف فئة جديدة'),
(4, 'Category Name', 'اسم الفئة'),
(4, 'Enter your category name', 'أدخل اسم فئتك'),
(4, 'Enter your unique category name', 'أدخل اسم فئتك الفريد'),
(4, 'Pick Your Icon', 'اختر الرمز الخاص بك'),
(4, 'Pick your category icon', 'اختر أيقونة فئتك'),
(4, 'Keywords', 'الكلمات الرئيسية'),
(4, 'optional', 'خياري'),
(4, 'Category Description', 'وصف الفئة'),
(4, 'Enter your description', 'أدخل وصفك'),
(4, 'Thumbnail', 'الصورة المصغرة'),
(4, 'Category logo', 'شعار الفئة'),
(4, 'Category added successfully', 'أضافت الفئة بنجاح'),
(4, 'Add', 'يضيف'),
(4, 'Edit category', 'تحرير الفئة'),
(4, 'Create course', 'إنشاء دورة'),
(4, 'Enter Course Title', 'أدخل عنوان الدورة'),
(4, 'Short Description', 'وصف قصير'),
(4, 'Enter Short Description', 'أدخل وصفًا قصيرًا'),
(4, 'Enter Description', 'أدخل الوصف'),
(4, 'Create as', 'إنشاء AS'),
(4, 'Select a category', 'حدد فئة'),
(4, 'Course level', 'مستوى الدورة'),
(4, 'Select your course level', 'حدد مستوى الدورة التدريبية الخاصة بك'),
(4, 'Made in', 'صنع في'),
(4, 'Select your course language', 'حدد لغة الدورة التدريبية الخاصة بك'),
(4, 'Pricing type', 'نوع التسعير'),
(4, 'Enter your course price', 'أدخل سعر الدورة التدريبية الخاصة بك'),
(4, 'Check if this course has discount', 'تحقق مما إذا كانت هذه الدورة تحتوي على خصم'),
(4, 'Discounted price', 'سعر مخفض'),
(4, 'Enter your discount price', 'أدخل سعر الخصم الخاص بك'),
(4, 'Finish!', 'ينهي!'),
(4, 'Course added successfully', 'تمت إضافة بالطبع بنجاح'),
(4, 'Edit course', 'تحرير الدورة'),
(4, 'Editing', 'التحرير'),
(4, 'Help', 'يساعد'),
(4, 'Frontend View', 'عرض الواجهة'),
(4, 'Course Player', 'لاعب المسار'),
(4, 'Curriculum', 'مقرر'),
(4, 'Basic', 'أساسي'),
(4, 'Live Class', 'فئة حية'),
(4, 'Pricing', 'التسعير'),
(4, 'Info', 'معلومات'),
(4, 'Media', 'وسائط'),
(4, 'SEO', 'كبار المسئولين الاقتصاديين'),
(4, 'Add new section', 'أضف قسمًا جديدًا'),
(4, 'Add section', 'إضافة القسم'),
(4, 'Add a new Section', 'أضف قسمًا جديدًا'),
(4, 'Create bootcamp', 'إنشاء Bootcamp'),
(4, 'Check if this bootcamp has discount', 'تحقق مما إذا كان هذا المعسكر لديه خصم'),
(4, 'Publish Date', 'تاريخ النشر'),
(4, 'Bootcamp Category', 'فئة Bootcamp'),
(4, 'No data found', 'لم يتم العثور على بيانات'),
(4, 'Add category', 'إضافة الفئة'),
(4, 'Category has been created.', 'تم إنشاء الفئة.'),
(4, 'Total bootcamps', 'إجمالي المعسكرات'),
(4, 'Bootcamp has been created.', 'تم إنشاء Bootcamp.'),
(4, 'Edit bootcamp', 'تحرير Bootcamp'),
(4, 'Frontent View', 'عرض الواجهة'),
(4, 'Create Student', 'إنشاء الطالب'),
(4, 'Student Info', 'معلومات الطالب'),
(4, 'Login Credentials', 'بيانات الاعتماد تسجيل الدخول'),
(4, 'Social Links', 'الروابط الاجتماعية'),
(4, 'Name', 'اسم'),
(4, 'Biography', 'سيرة'),
(4, 'User image', 'صورة المستخدم'),
(4, 'Facebook', 'فيسبوك'),
(4, 'Twitter', 'تغريد'),
(4, 'Linkedin', 'LinkedIn'),
(4, 'Student add successfully', 'يضيف الطالب بنجاح'),
(4, 'Student List', 'قائمة الطلاب'),
(4, 'Export', 'يصدّر'),
(4, 'PDF', 'PDF'),
(4, 'Print', 'مطبعة'),
(4, 'Search user', 'مستخدم البحث'),
(4, 'Search', 'يبحث'),
(4, 'Enrolled Course', 'مسجل المسجل'),
(4, 'Options', 'خيارات'),
(4, 'Email Verification', 'التحقق من البريد الإلكتروني'),
(4, 'Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn''t receive the email, we will gladly send you another.', 'شكرا للتسجيل!قبل البدء ، هل يمكنك التحقق من عنوان بريدك الإلكتروني من خلال النقر على الرابط الذي أرسلناه إليك بالبريد الإلكتروني؟إذا لم تتلق البريد الإلكتروني ، فسوف نرسل لك بكل سرور آخر.'),
(4, 'Resend Verification Email', 'إعادة إرسال البريد الإلكتروني للتحقق'),
(4, 'My Courses', 'دوراتي'),
(4, 'My Bootcamps', 'المعسكرات الخاصة بي'),
(4, 'Upload picture', 'تحميل الصورة'),
(4, 'Upload New', 'تحميل جديد'),
(4, 'My Teams', 'فرق بلدي'),
(4, 'Please try using the appropriate keywords.', 'يرجى محاولة استخدام الكلمات الرئيسية المناسبة.'),
(4, 'Bootcamps', 'Bootcamps'),
(4, 'All Bootcamps', 'جميع المعسكرات'),
(4, 'Class', 'فصل'),
(4, 'View Details', 'عرض التفاصيل'),
(4, 'Buy Now', 'اشتري الآن'),
(4, 'Item is already purchased.', 'تم شراء العنصر بالفعل.'),
(4, 'Bootcamp payment', 'الدفع Bootcamp'),
(4, 'Order summary', 'ملخص الطلب'),
(4, 'Cancel Payment', 'إلغاء الدفع'),
(4, 'Select payment gateway', 'حدد بوابة الدفع'),
(4, 'Item List', 'قائمة العناصر'),
(4, 'Total', 'المجموع'),
(4, 'Grand Total', 'المجموع الإجمالي'),
(4, 'Reviews', 'المراجعات'),
(4, 'lesson', 'درس'),
(4, 'Students', 'طلاب'),
(4, 'Terms and condition', 'الشروط والحالة'),
(4, 'Terms', 'شروط'),
(4, 'WELLCOME TO CHEF', 'مرحبا بكم في الشيف'),
(4, 'Visit Courses', 'زيارة الدورات'),
(4, 'Enrolled Learners', 'المتعلمين المسجلين'),
(4, 'Online Instructors', 'المدربون عبر الإنترنت'),
(4, 'Latest Top Skills', 'أحدث المهارات العليا'),
(4, 'Awesome  site the top advertising been business.', 'موقع رائع كان الإعلان أفضل الأعمال.'),
(4, 'Industry Experts', 'خبراء الصناعة'),
(4, 'Learning From Anywhere', 'التعلم من أي مكان'),
(4, 'Top Rated Courses', 'أفضل دورات تصنيف'),
(4, 'Upcoming Courses', 'الدورات القادمة'),
(4, 'Highlights the latest courses set to launch, giving students a sneak peek at new opportunities for learning and skill development. Stay ahead with our curated selection of upcoming educational offerings!', 'يسلط الضوء على أحدث الدورات التدريبية التي يتم إطلاقها ، مما يمنح الطلاب نظرة خاطفة على فرص جديدة للتعلم وتنمية المهارات.ابق في المقدمة مع مجموعة مختارة من العروض التعليمية القادمة!'),
(4, 'Featured Courses', 'دورات مميزة'),
(4, 'Think more clearly', 'فكر بشكل أكثر وضوحًا'),
(4, 'Awesome  site. on the top advertising a business online includes assembling Having the most keep.', 'موقع رائع.في أعلى الإعلان ، يتضمن شركة Business Online تجميع أكثر الاحتفاظ بها.'),
(4, 'Video title', 'عنوان الفيديو'),
(4, 'Our Popular Instructor', 'مدربنا الشعبي'),
(4, 'Highlights our most sought-after educator, recognized for their engaging teaching style and exceptional course content. Discover their expertise and join the many students who have benefited from their classes!', 'يسلط الضوء على المعلم الأكثر رواجًا لدينا ، معترف به لأسلوب التدريس الجذاب ومحتوى الدورة التدريبية الاستثنائية.اكتشف خبرتهم وانضم إلى العديد من الطلاب الذين استفادوا من فصولهم!'),
(4, 'Frequently Asked Questions?', 'أسئلة طالبا في كثير من الأحيان؟'),
(4, 'FAQ provides quick answers to common inquiries, helping users resolve doubts efficiently.', 'تقدم الأسئلة الشائعة إجابات سريعة للاستفسارات الشائعة ، مما يساعد المستخدمين على حل الشكوك بكفاءة.'),
(4, 'Follow The Latest News', 'اتبع آخر الأخبار'),
(4, 'Top Courses', 'الدورات العليا'),
(4, 'lessons', 'الدروس'),
(4, 'Subscribe to our newsletter to get latest updates', 'اشترك في النشرة الإخبارية للحصول على آخر التحديثات'),
(4, 'Subscribe to stay tuned for new latest updates and offer. Let''s do it! ', 'اشترك في التزامنا للحصول على آخر تحديثات وعرض جديد.دعونا نفعل ذلك!'),
(4, 'Subscribe', 'يشترك'),
(4, 'Read our privacy policy', 'اقرأ سياسة الخصوصية الخاصة بنا'),
(4, 'Here', 'هنا'),
(4, 'Blog category', 'فئة المدونة'),
(4, 'Subtitle', 'الترجمة'),
(4, '(80  Character)', '(80 حرف)'),
(4, 'Category add successfully', 'الفئة إضافة بنجاح'),
(4, 'Total number of blog', 'إجمالي عدد المدونة'),
(4, 'Add new blog', 'أضف مدونة جديدة'),
(4, 'Search Title', 'عنوان البحث'),
(4, 'Add Blog', 'أضف مدونة'),
(4, 'Enter blog title', 'أدخل عنوان المدونة'),
(4, 'Writing your keyword and hit htw enter button', 'كتابة كلمتك الرئيسية واضغط على زر إدخال HTW'),
(4, 'Blog banner', 'لافتة المدونة'),
(4, 'Blog thumbnail', 'Thumbnail المدونة'),
(4, 'Would you like to designate it as popular?', 'هل ترغب في تعيينه على أنه شائع؟'),
(4, 'Blog add successfully', 'إضافة المدونة بنجاح'),
(4, 'Creator', 'الخالق'),
(4, 'View on frontend', 'عرض على الواجهة الأمامية'),
(4, 'Read More', 'اقرأ المزيد'),
(4, 'Get Started Now', 'ابدأ الآن'),
(4, 'Creating A Community Of Life Long Learners', 'خلق مجتمع من المتعلمين الطويل الحياة'),
(4, 'Our LMS goes beyond just providing courses. It''s a platform designed to ignite curiosity and empower your lifelong learning journey.  This supportive community provides a space to ask questions, no matter how big or small, and receive insightful answers from experienced learners and subject-matter experts.', 'LMS لدينا يتجاوز مجرد توفير الدورات.إنها منصة مصممة لإشعال الفضول وتمكين رحلة التعلم مدى الحياة.يوفر هذا المجتمع الداعم مساحة لطرح الأسئلة ، بغض النظر عن حجمها الكبير أو الصغير ، وتلقي إجابات ثاقبة من المتعلمين ذوي الخبرة وخبراء الموضوع.'),
(4, 'Share your own experiences and challenges, and find encouragement and inspiration from others on a similar path. The diverse perspectives within our community will broaden your horizons and challenge your thinking, fostering a deeper understanding and a richer learning experience.  Together, we''ll transform learning from a solitary pursuit into a collaborative adventure, where shared knowledge fuels individual growth and collective discovery.', 'شارك خبراتك وتحدياتك ، وابحث عن التشجيع والإلهام من الآخرين على مسار مماثل.إن المنظورات المتنوعة داخل مجتمعنا ستوسع آفاقك وتحدي تفكيرك ، وتعزيز فهم أعمق وتجربة تعليمية أكثر ثراءً.سنقوم معًا بتحويل التعلم من المطاردة الانفرادية إلى مغامرة تعاونية ، حيث تقوم المعرفة المشتركة بتغذية النمو الفردي والاكتشاف الجماعي.'),
(4, 'Learn more about us', 'تعرف على المزيد عنا'),
(4, 'Our Online Courses', 'دوراتنا على الإنترنت'),
(4, 'See More', 'رؤية المزيد'),
(4, 'Our Blog', 'مدونتنا'),
(4, 'LEARN FROM TODAY', 'تعلم من اليوم'),
(4, 'Watch Video', 'مشاهدة الفيديو'),
(4, 'Expert Mentors', 'مرشدون الخبراء'),
(4, 'Students Globally', 'الطلاب على مستوى العالم'),
(4, 'Cost Free Course', 'دورة مجانية التكلفة'),
(4, 'False', 'nan'),
(4, 'Having enjoyed a breathlessly successful 2015, there can be no DJ  dynamic set of teaching tools Billed to be deployed.', 'بعد أن استمتعت بعام 2015 ناجحًا بشكل لا تنفث ، لا يمكن أن يكون هناك مجموعة ديناميكية من أدوات التدريس التي يتم نشرها.'),
(4, 'Student email verification', 'التحقق من البريد الإلكتروني الطالب'),
(4, 'Disabled', 'عاجز'),
(4, 'Frontend Settings', 'إعدادات الواجهة الأمامية'),
(4, 'Motivational Speech', 'الكلام التحفيزي'),
(4, 'Website FAQS', 'الأسئلة الشائعة عن موقع الويب'),
(4, 'Contact Information', 'معلومات الاتصال'),
(4, 'User Reviews', 'مراجعات المستخدم'),
(4, 'Logo & Images', 'الشعار والصور'),
(4, 'Frontend website settings', 'إعدادات موقع الويب الأمامي'),
(4, 'Banner title', 'لافتة لافتة'),
(4, 'Banner sub title', 'اللافتة الفرعية لقب'),
(4, 'Promo Video Provider', 'مزود الفيديو الترويجي'),
(4, 'Youtube Video Link', 'رابط فيديو يوتيوب'),
(4, 'Vimeo Video Link', 'رابط فيديو Vimeo'),
(4, 'HTML5 Video link', 'HTML5 رابط الفيديو'),
(4, 'Promo video link', 'رابط الفيديو الترويجي'),
(4, 'Cookie status', 'حالة ملفات تعريف الارتباط'),
(4, 'Cookie note', 'ملاحظة ملفات تعريف الارتباط'),
(4, 'Refund policy', 'سياسة الاسترداد'),
(4, 'Mobile App download Link', 'رابط تنزيل تطبيق الجوال'),
(4, 'Update Settings', 'تحديث الإعدادات'),
(4, 'designation', 'تعيين'),
(4, 'Question', 'سؤال'),
(4, 'Write a question', 'اكتب سؤالاً'),
(4, 'Answer', 'إجابة'),
(4, 'Write a question answer', 'اكتب إجابة سؤال'),
(4, 'Contact Email', 'اتصل بالبريد الإلكتروني'),
(4, 'Phone Number', 'رقم التليفون'),
(4, 'Office Hours', 'ساعات العمل'),
(4, 'Location', 'موقع'),
(4, 'Latitude', 'خط العرض'),
(4, 'Longitude', 'خط الطول'),
(4, 'Recaptcha settings', 'إعدادات recaptcha'),
(4, 'Recaptcha status', 'حالة recaptcha'),
(4, 'Recaptcha sitekey', 'recaptcha sitekey'),
(4, 'Recaptcha secretkey', 'recaptcha secretkey'),
(4, 'Update recaptcha settings', 'تحديث إعدادات recaptcha'),
(4, 'Review', 'مراجعة'),
(4, 'Add new Review', 'أضف مراجعة جديدة'),
(4, 'Click here to choose a banner image', 'انقر هنا لاختيار صورة لافتة'),
(4, 'Upload banner image', 'تحميل صورة لافتة'),
(4, 'Click here to choose a light logo', 'انقر هنا لاختيار شعار الضوء'),
(4, 'Upload light logo', 'تحميل شعار الضوء'),
(4, 'Click here to choose a dark logo', 'انقر هنا لاختيار شعار مظلم'),
(4, 'Upload dark logo', 'تحميل الشعار المظلم'),
(4, 'Click here to choose a favicon', 'انقر هنا لاختيار Favicon'),
(4, 'Upload favicon', 'تحميل favicon'),
(4, 'Frontend settings update successfully', 'تحديث إعدادات الواجهة بنجاح'),
(4, 'User already register and signing up for using it', 'يسجل المستخدم بالفعل والتسجيل لاستخدامه'),
(4, 'Get Courses', 'الحصول على دورات'),
(4, 'Start Learning', 'ابدأ في التعلم'),
(4, 'Coding', 'الترميز'),
(4, 'Languages', 'اللغات'),
(4, 'The industry''s standard dummy text ever since the  unknown printer took a galley of type and scrambled', 'النص الوهمي القياسي للصناعة منذ أن أخذت الطابعة غير المعروفة من النوع واضطرابها'),
(4, 'Online Courses', 'الدورات عبر الإنترنت'),
(4, 'Top Instructors', 'كبار المدربين'),
(4, 'Online Certificates', 'شهادات عبر الإنترنت'),
(4, 'Pick A Course To', 'اختر دورة إلى'),
(4, 'Download our mobile app, start learning', 'قم بتنزيل تطبيق الهاتف المحمول الخاص بنا ، وابدأ في التعلم'),
(4, 'Academy', 'أكاديمية'),
(4, 'Download Now', 'تحميل الآن'),
(4, 'Frequently Asked', 'كثيرا ما يطلب'),
(4, 'Questions', 'أسئلة'),
(4, 'What Our', 'ما لدينا'),
(4, 'Have To Say', 'يجب أن أقول'),
(4, 'Get News with', 'الحصول على الأخبار مع'),
(4, 'comment', 'تعليق'),
(4, 'Course Manager', 'مدير الدورة'),
(4, 'Active courses', 'دورات نشطة'),
(4, 'Pending courses', 'دورات معلقة'),
(4, 'Free courses', 'دورات مجانية'),
(4, 'Paid courses', 'دورات مدفوعة الأجر'),
(4, 'All', 'الجميع'),
(4, 'Apply', 'يتقدم'),
(4, 'Lesson & Section', 'الدرس والقسم'),
(4, 'Enrolled Student', 'طالب مسجل'),
(4, 'Section', 'قسم'),
(4, 'View Course On Frontend', 'عرض الدورة التدريبية على الواجهة الأمامية'),
(4, 'Go To Course Playing Page', 'اذهب إلى صفحة لعب الدورة التدريبية'),
(4, 'Duplicate Course', 'دورة مكررة'),
(4, 'Make As Active', 'اجعل نشطة'),
(4, 'Delete Course', 'حذف الدورة'),
(4, 'Course updated successfully', 'تم تحديث الدورة بنجاح'),
(4, 'Multi language setting', 'إعداد لغة متعددة'),
(4, 'Language list', 'قائمة اللغة'),
(4, 'Add Language', 'أضف اللغة'),
(4, 'Import Language', 'استيراد لغة'),
(4, 'Direction', 'اتجاه'),
(4, 'Option', 'خيار'),
(4, 'LTR', 'LTR'),
(4, 'RTL', 'RTL'),
(4, 'Edit phrase', 'تحرير العبارة'),
(4, 'Add new language', 'أضف لغة جديدة'),
(4, 'No special character or space is allowed. Valid examples: French, Spanish, Bengali etc', 'لا يُسمح بأي شخصية أو مساحة خاصة.أمثلة صالحة: الفرنسية والإسبانية والبنغالية وما إلى ذلك'),
(4, 'Save', 'يحفظ'),
(4, 'Import your language files from here. (Ex: english.json)', 'استيراد ملفات لغتك من هنا.(على سبيل المثال: English.json)'),
(4, 'Import', 'يستورد'),
(4, 'phrase_updated', 'phrase_updated'),
(4, 'Direction has been updated', 'تم تحديث الاتجاه'),
(4, 'Education For Eeveryone', 'التعليم للجميع'),
(4, 'Search here', 'ابحث هنا'),
(4, 'Online Instructor have a new ideas every week.', 'المدرب عبر الإنترنت لديه أفكار جديدة كل أسبوع.'),
(4, 'Special Featured Course.', 'دورة مميزة خاصة.'),
(4, 'View More', 'عرض المزيد'),
(4, 'Know About Academy LMS Learning Platform', 'تعرف على منصة التعلم في أكاديمية LMS'),
(4, 'Far far away, behind the word mountains, far from the away countries Vokalia and Consonantia, there live the blind texts.', 'بعيدا بعيدًا ، خلف كلمة الجبال ، بعيدًا عن البلدان البعيدة ، فوكاليا و Contonantia ، تعيش النصوص العمياء.'),
(4, 'Free Resources Learning English for Beginner', 'الموارد المجانية تعلم اللغة الإنجليزية للمبتدئين'),
(4, 'Far far away, behind the word mountains, far from the away countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.', 'بعيدا بعيدًا ، خلف كلمة الجبال ، بعيدًا عن البلدان البعيدة ، فوكاليا و Contonantia ، تعيش النصوص العمياء.منفصلين ويعيشون في مرجعية مباشرة على ساحل الدلالات ، محيط لغة كبيرة.'),
(4, 'Instructor have a new ideas every week.', 'المدرب لديه أفكار جديدة كل أسبوع.'),
(4, 'Meet Our Team', 'قابل فريقنا'),
(4, 'Download our mobile app, start learning today', 'قم بتنزيل تطبيق الهاتف المحمول الخاص بنا ، ابدأ في التعلم اليوم'),
(4, 'Includes all Course && Features', 'يتضمن كل ميزات الدورة و'),
(4, 'Get Bundle', 'احصل على حزمة'),
(4, 'Create Instructor', 'إنشاء مدرب'),
(4, 'Instructor Info', 'معلومات المدرب'),
(4, 'Payment Information', 'معلومات الدفع'),
(4, 'Instructor add successfully', 'المدرب يضيف بنجاح'),
(4, 'Instructor List', 'قائمة المدربين'),
(4, 'Number Of Course', 'عدد بالطبع'),
(4, 'View courses', 'عرض الدورات'),
(4, 'Make As Inactive', 'اجعل غير نشط'),
(4, 'Enroll Students', 'تسجيل الطلاب'),
(4, 'Course to enrol', 'بالطبع للتسجيل'),
(4, 'Select a course', 'حدد دورة'),
(4, 'Enroll History', 'تسجيل التاريخ'),
(4, 'Add new enrollment', 'أضف الالتحاق الجديد'),
(4, 'Enrolled Date', 'التاريخ المسجل'),
(4, 'Expiry Date', 'تاريخ انتهاء الصلاحية'),
(4, 'Lifetime access', 'الوصول مدى الحياة'),
(4, 'Add Review', 'إضافة المراجعة'),
(4, 'Select User', 'حدد المستخدم'),
(4, 'Select an user', 'حدد مستخدم'),
(4, 'Rating', 'تصنيف'),
(4, 'Select a Rating', 'حدد تصنيف'),
(4, 'Review added successfull', 'مراجعة أضيفت بنجاح'),
(4, 'About Us Image', 'عنا صورة'),
(4, 'Faq  Image', 'صورة الأسئلة الشائعة'),
(4, 'Faq Image', 'صورة الأسئلة الشائعة'),
(4, 'Slider image & video link', 'شريط التمرير والفيديو رابط'),
(4, 'Add Image', 'أضف الصورة'),
(4, 'Add Video Link', 'أضف رابط الفيديو'),
(4, 'Homepage updated successfully', 'تم تحديث الصفحة الرئيسية بنجاح'),
(4, 'Duration', 'مدة'),
(4, 'Course Details', 'تفاصيل الدورة'),
(4, 'Certificate Course', 'دورة شهادة'),
(4, 'Overview', 'ملخص'),
(4, 'Details', 'تفاصيل'),
(4, 'Course Overview', 'نظرة عامة على الدورة'),
(4, 'No Course Description', 'لا وصف الدورة'),
(4, 'FAQ area empty', 'منطقة الأسئلة الشائعة فارغة'),
(4, 'Course curriculum', 'المناهج الدراسية'),
(4, 'Course curriculum Empty', 'المناهج الدراسية الفارغة'),
(4, 'Requirment', 'مطلب'),
(4, 'Outcomes', 'النتائج'),
(4, 'Rate this course : ', 'قيم هذه الدورة:'),
(4, 'Remove all', 'إزالة كل شيء'),
(4, 'Write a reveiw ...', 'اكتب مراجعة ...'),
(4, 'Add to cart', 'أضف إلى السلة'),
(4, 'Share', 'يشارك'),
(4, 'Share on Facebook', 'شارك على Facebook'),
(4, 'Share on Twitter', 'شارك على Twitter'),
(4, 'Share on Whatsapp', 'شارك على WhatsApp'),
(4, 'Share on Linkedin', 'مشاركة على LinkedIn'),
(4, 'Certificate', 'شهادة'),
(4, 'Certificate template', 'قالب الشهادة'),
(4, 'Build your certificate', 'بناء شهادتك'),
(4, 'Upload your certificate template', 'قم بتحميل قالب الشهادة الخاص بك'),
(4, 'Upload', 'رفع'),
(4, 'Certificate elements', 'عناصر الشهادة'),
(4, 'Available Variable Data', 'البيانات المتغيرة المتاحة'),
(4, 'Add a new element', 'أضف عنصرًا جديدًا'),
(4, 'Enter Text with variable data', 'أدخل النص مع بيانات متغيرة'),
(4, 'Total Lesson', 'الدرس الكلي'),
(4, 'Choice a font-family', 'اختيار أسرة الخط'),
(4, 'Default', 'تقصير'),
(4, 'Pinyon Script', 'نص بينيون'),
(4, 'Font Size', 'حجم الخط'),
(4, 'Save Template', 'حفظ القالب'),
(4, 'Certificate builder template has been updated', 'تم تحديث قالب منشئ الشهادة'),
(4, 'Progress', 'تقدم'),
(4, 'Start Now', 'ابدأ الآن'),
(4, 'Course Playing Page', 'صفحة لعب الدورة'),
(4, 'Summary', 'ملخص'),
(4, 'Forum', 'المنتدى'),
(4, 'Class Schedules', 'جداول الفصل'),
(4, 'Topic', 'عنوان'),
(4, 'Date & time', 'التاريخ والوقت'),
(4, 'Keep up the great work!', 'استمروا في العمل الرائع!'),
(4, 'Your dedication to ongoing progress is inspiring.', 'تفانيك في التقدم المستمر أمر ملهم.'),
(4, 'Every step forward is a testament to your commitment to growth and excellence.', 'كل خطوة إلى الأمام هي شهادة على التزامك بالنمو والتميز.'),
(4, 'Stay focused, stay determined, and continue to push yourself to new heights.', 'حافظ على التركيز ، والبقاء مصممًا ، واستمر في دفع نفسك إلى آفاق جديدة.'),
(4, 'You have got this!', 'لقد حصلت على هذا!'),
(4, 'Search answers here', 'البحث عن الإجابات هنا'),
(4, 'Questions in this course', 'أسئلة في هذه الدورة'),
(4, 'Ask question', 'اطرح سؤال'),
(4, 'Completed', 'مكتمل'),
(4, 'Enter title', 'أدخل العنوان'),
(4, 'Section added successfully', 'أضاف القسم بنجاح'),
(4, 'Add new lesson', 'أضف درسًا جديدًا'),
(4, 'Add lesson', 'أضف الدرس'),
(4, 'Add new quiz', 'أضف اختبار جديد'),
(4, 'Add quiz', 'إضافة مسابقة'),
(4, 'Sort sections', 'فرز الأقسام'),
(4, 'Sort Section', 'قسم الفرز'),
(4, 'Edit section', 'تحرير قسم'),
(4, 'Delete section', 'حذف القسم'),
(4, 'No lessons are available.', 'لا توجد دروس متوفرة.'),
(4, 'Select lesson type', 'حدد نوع الدرس'),
(4, 'YouTube Video', 'فيديو يوتيوب'),
(4, 'Vimeo Video', 'فيديو Vimeo'),
(4, 'Video file', 'ملف الفيديو'),
(4, 'Video url [ .mp4 ]', 'عنوان URL للفيديو [.mp4]'),
(4, 'Google drive video', 'فيديو Google Drive'),
(4, 'Document file', 'ملف المستند'),
(4, 'Text', 'نص'),
(4, 'Iframe embed', 'Iframe تضمين'),
(4, 'Next', 'التالي'),
(4, 'Lesson type', 'نوع الدرس'),
(4, 'Change', 'يتغير'),
(4, 'Enter your text', 'أدخل النص الخاص بك'),
(4, 'Do you want to keep it free as a preview lesson', 'هل تريد أن تبقيها مجانية كدرس معاينة'),
(4, 'Mark as free lesson', 'ضع علامة على الدرس الحر'),
(4, 'lesson added successfully', 'الدرس أضيفت بنجاح'),
(4, 'Sort lessons', 'فرز الدروس'),
(4, 'Edit lesson', 'تحرير الدرس'),
(4, 'Delete lesson', 'حذف الدرس'),
(4, 'Congratulations!', 'مبروك!'),
(4, 'Your hard work has paid off. Here is to new beginnings and endless opportunities ahead!', 'لقد أثمر عملك الشاق.هنا لبدايات جديدة وفرص لا نهاية لها في المستقبل!'),
(4, 'Get Certificate', 'الحصول على شهادة'),
(4, 'Download Certificate', 'تنزيل شهادة'),
(4, 'Download', 'تحميل'),
(4, 'Auto', 'آلي'),
(4, 'Continue', 'يكمل'),
(4, 'Shopping cart', 'عربة التسوق'),
(4, 'Cart items', 'عناصر عربة'),
(4, 'Payment summary', 'ملخص الدفع'),
(4, 'Sub total', 'مجموع'),
(4, 'Tax', 'ضريبة'),
(4, '%', '٪'),
(4, 'Apply coupon', 'تطبيق القسيمة'),
(4, 'Send as a gift', 'أرسل كهدية'),
(4, 'Enter user email', 'أدخل البريد الإلكتروني للمستخدم'),
(4, 'Continue to payment', 'تواصل الدفع'),
(4, 'Payment failed! Please try again.', 'فشل الدفع!من فضلك حاول مرة أخرى.'),
(4, 'Parent category', 'فئة الوالدين'),
(4, '- Mark it as parent -', '- ضع علامة عليه كوالد -'),
(4, 'Choose category thumbnail', 'اختر فئة الصورة المصغرة'),
(4, 'Choose category Logo', 'اختر شعار الفئة'),
(4, 'Category updated successfully', 'تحديث الفئة بنجاح'),
(4, 'Enable the Fileinfo extension on your server to upload files.', 'تمكين ملحق FileInfo على الخادم الخاص بك لتحميل الملفات.'),
(4, 'Fileinfo extension', 'ملحق FileInfo'),
(4, 'Enable this Fileinfo extension on your server to upload files', 'تمكين ملحق FileInfo على الخادم الخاص بك لتحميل الملفات'),
(4, 'paytm merchant key', 'مفتاح تاجر Paytm'),
(4, 'paytm merchant mid', 'Paytm Merchant Mid'),
(4, 'paytm merchant website', 'موقع Paytm Merchant'),
(4, 'industry type id', 'معرف نوع الصناعة'),
(4, 'channel id', 'معرف القناة'),
(4, 'Payment settings update successfully', 'تحديث إعدادات الدفع بنجاح'),
(4, 'Configure ZOOM server-to-server-oauth credentials', 'تكوين بيانات اعتماد خادم Zoom إلى الخادم'),
(4, 'Account Email', 'البريد الإلكتروني حساب'),
(4, 'Account ID', 'معرف الحساب'),
(4, 'Client ID', 'معرف العميل'),
(4, 'Client Secret', 'سر العميل'),
(4, 'Do you want to use Web SDK for your live class?', 'هل تريد استخدام الويب SDK لفصلك المباشر؟'),
(4, 'Meeting SDK Client ID', 'اجتماع معرف عميل SDK'),
(4, 'Meeting SDK Client Secret', 'مقابلة سر عميل SDK'),
(4, 'Enroll delete successfully', 'تسجيل الحذف بنجاح'),
(4, '500 error found', 'تم العثور على 500 خطأ'),
(4, 'A technical error has occurred', 'حدث خطأ فني'),
(4, 'Please contact with site administrator', 'يرجى الاتصال بمسؤول الموقع'),
(4, 'please_do_not_refresh_this_page', 'issy_do_not_refresh_this_page'),
(4, 'Please do not refresh this page', 'من فضلك لا تحديث هذه الصفحة'),
(4, 'User', 'مستخدم'),
(4, 'Item', 'غرض'),
(4, 'Paid amount', 'المبلغ المدفوع'),
(4, 'Payment method', 'طريقة الدفع'),
(4, 'Purchased date', 'موعد تم شراؤه'),
(4, 'Invoice', 'فاتورة'),
(4, 'Select an option', 'حدد خيار'),
(4, 'Total Mark', 'علامة مجموع'),
(4, 'Pass Mark', 'مارك'),
(4, 'Retake', 'إعادة'),
(4, 'Quiz has been created.', 'تم إنشاء مسابقة.'),
(4, 'Result', 'نتيجة'),
(4, 'Edit quiz', 'تحرير مسابقة'),
(4, 'Update Quiz', 'تحديث مسابقة'),
(4, 'Add Question', 'أضف سؤالا'),
(4, 'Question Type', 'نوع السؤال'),
(4, 'Multiple Choice', 'الاختيار من متعدد'),
(4, 'Fill in the blanks', 'املأ الفراغات'),
(4, 'True or False', 'صحيح أو خطأ'),
(4, 'Write question', 'اكتب السؤال'),
(4, 'Your questions here', 'أسئلتك هنا'),
(4, 'You can keep multiple options. Just put an option and hit enter.', 'يمكنك الاحتفاظ بخيارات متعددة.فقط ضع خيارًا واضغط على Enter.'),
(4, 'You can select multiple answers.', 'يمكنك تحديد إجابات متعددة.'),
(4, 'Manage Course', 'إدارة الدورة'),
(4, 'Time left : ', 'الوقت المتبقي:'),
(4, 'Hour', 'ساعة'),
(4, 'Minute', 'دقيقة'),
(4, 'Second', 'ثانية'),
(4, 'Total Marks', 'إجمالي علامات'),
(4, 'Pass Marks', 'علامات المرور'),
(4, 'Attempts', 'محاولات'),
(4, 'Total Question', 'السؤال الكلي'),
(4, 'Start Quiz', 'ابدأ الاختبار'),
(4, 'Quiz has been updated.', 'تم تحديث مسابقة.'),
(4, 'Question has been added.', 'تمت إضافة سؤال.'),
(4, 'Sort Questions', 'فرز الأسئلة'),
(4, 'Edit Question', 'تحرير السؤال'),
(4, 'Update Question', 'تحديث السؤال'),
(4, 'Watermark Type', 'نوع العلامة المائية'),
(4, 'Js Watermark', 'JS Watermark'),
(4, 'FFMpeg', 'FFMPEG'),
(4, 'Watermark', 'العلامة المائية'),
(4, 'Opacity', 'الغضب'),
(4, 'Opacity (0 - 100)', 'التعتيم (0 - 100)'),
(4, 'Width', 'عرض'),
(4, 'Width (px)', 'العرض (PX)'),
(4, 'Height', 'ارتفاع'),
(4, 'Height (px)', 'الارتفاع (PX)'),
(4, 'Top', 'قمة'),
(4, 'Top (px)', 'أعلى (PX)'),
(4, 'Left (px)', 'اليسار (PX)'),
(4, 'Enter your html5 video url', 'أدخل عنوان URL فيديو HTML5 الخاص بك'),
(4, 'The image size should be', 'يجب أن يكون حجم الصورة'),
(4, 'Caption', 'التسمية التوضيحية'),
(4, '.vtt', '.vtt'),
(4, 'Animation speed', 'سرعة الرسوم المتحركة'),
(4, 'Second (0 - 200)', 'الثانية (0 - 200)'),
(4, 'Your changes has been saved.', 'تم حفظ التغييرات الخاصة بك.'),
(4, 'Second (0 - 10000)', 'الثانية (0 - 10000)'),
(4, 'by', 'بواسطة'),
(4, 'Find A Tutor', 'ابحث عن مدرس'),
(4, 'Tutor Booking', 'الحجز المعلم'),
(4, 'Subjects', 'الموضوعات'),
(4, 'Subject Category', 'فئة الموضوع'),
(4, 'Update Student', 'تحديث الطالب'),
(4, 'Student update successfully', 'تحديث الطالب بنجاح'),
(4, 'My Bookings', 'حجوزاتي'),
(4, 'Signin with Google', 'تسجيل الدخول مع Google'),
(4, 'Signin with Linkedin', 'تسجيل الدخول مع LinkedIn'),
(4, 'Signin with Facebook', 'تسجيل الدخول مع Facebook'),
(4, 'Login with Google', 'تسجيل الدخول مع Google'),
(4, 'Login with Linkedin', 'تسجيل الدخول مع LinkedIn'),
(4, 'Tutor subjects', 'موضوعات المعلم'),
(4, 'Add new subject', 'أضف موضوعًا جديدًا'),
(4, 'Language added successfully', 'أضافت اللغة بنجاح'),
(4, 'Delete language', 'حذف اللغة'),
(4, 'Edit Instructor', 'تحرير مدرب'),
(4, 'Instructor update successfully', 'تحديث المدرب بنجاح'),
(4, 'Already have account.', 'لديك بالفعل حساب.'),
(4, 'Sign in', 'تسجيل الدخول'),
(4, 'Continue with Google', 'تابع مع Google'),
(4, 'Continue with Linkedin', 'تابع مع LinkedIn'),
(4, 'Forgot Password', 'هل نسيت كلمة السر'),
(4, 'Submit your account email address.', 'أرسل عنوان بريدك الإلكتروني حسابك.'),
(4, 'Enter Your Email', 'أدخل بريدك الإلكتروني'),
(4, 'Send Request', 'إرسال الطلب'),
(4, 'Back to login page', 'العودة إلى صفحة تسجيل الدخول'),
(4, 'Notification settings', 'إعدادات الإخطار'),
(4, 'Protocol', 'بروتوكول'),
(4, 'Smtp crypto', 'SMTP Crypto'),
(4, 'Smtp host', 'مضيف SMTP'),
(4, 'Smtp port', 'منفذ SMTP'),
(4, 'Smtp from email', 'SMTP من البريد الإلكتروني'),
(4, 'Smtp username', 'اسم المستخدم SMTP'),
(4, 'Smtp password', 'كلمة مرور SMTP'),
(4, 'SMTP setting update successfully', 'تحديث إعداد SMTP بنجاح'),
(4, 'System settings update successfully', 'تحديث إعدادات النظام بنجاح'),
(4, 'Manage content', 'إدارة المحتوى'),
(4, 'Text editor', 'محرر النص'),
(4, 'Text color', 'لون النص'),
(4, 'Padding', 'حشوة'),
(4, 'Margin', 'هامِش'),
(4, 'Border', 'حدود'),
(4, 'none', 'لا أحد'),
(4, 'dashed', 'متقطع'),
(4, 'dotted', 'منقط'),
(4, 'Border roundness', 'جولة الحدود'),
(4, 'Border color', 'لون الحدود'),
(4, 'Background color', 'لون الخلفية'),
(4, 'Image editor', 'محرر الصور'),
(4, 'Sign Up with Google', 'اشترك مع Google'),
(4, 'Sign Up with LinkedIn', 'اشترك مع LinkedIn'),
(4, 'Start learning from the world''s pro', 'ابدأ في التعلم من المحترف في العالم'),
(4, 'instructors', 'المدربون'),
(4, 'We invites learners to explore courses designed by industry experts, offering cutting-edge content for skill development.', 'ندعو المتعلمين إلى استكشاف الدورات التدريبية التي صممها خبراء الصناعة ، وتقديم محتوى متطور لتطوير المهارات.'),
(4, 'Contact us', 'اتصل بنا'),
(4, 'We''re always here to help you.', 'نحن دائمًا هنا لمساعدتك.'),
(4, 'Our Address', 'عنواننا'),
(4, 'Our location', 'موقعنا'),
(4, 'Contact Info', 'معلومات الاتصال'),
(4, 'Open a chat or give us call at', 'افتح دردشة أو اتصل بنا على'),
(4, 'Send your message', 'أرسل رسالتك'),
(4, 'Send Message', 'أرسل رسالة'),
(4, 'Personal Information', 'معلومات شخصية'),
(4, 'Full Name', 'الاسم الكامل'),
(4, 'Website', 'موقع إلكتروني'),
(4, 'Skills', 'مهارات'),
(4, 'Fee', 'مصاريف'),
(4, 'Min', 'دقيقة'),
(4, 'Max', 'الأعلى'),
(4, 'Results', 'نتائج'),
(4, 'Enable drip content', 'تمكين محتوى التنقيط'),
(4, 'Off', 'عن'),
(4, 'On', 'على'),
(4, 'Drip Content', 'محتوى بالتنقيط'),
(4, 'Enroll Now', 'التسجيل الآن'),
(4, 'Discount type', 'نوع الخصم'),
(4, 'Clear', 'واضح'),
(4, 'Pay by Stripe', 'دفع عن طريق الشريط'),
(4, 'Purchasing', 'شراء'),
(4, 'Add a new live class', 'أضف فصلًا مباشرًا جديدًا'),
(4, 'Schedule a new live class', 'حدد موعدًا لصفًا مباشرًا جديدًا'),
(4, 'Class topic', 'موضوع الفصل'),
(4, 'Class Schedule', 'جدول الفصل'),
(4, 'Banner', 'لافتة'),
(4, 'Preview Video', 'معاينة الفيديو'),
(4, 'Supported URL', 'عنوان URL المدعوم'),
(4, 'or', 'أو'),
(4, 'Vimeo', 'Vimeo'),
(4, 'Preview Video File', 'معاينة ملف الفيديو'),
(4, 'Supported Video file', 'ملف الفيديو المدعوم'),
(4, 'mp4', 'MPP'),
(4, 'webm', 'WebM'),
(4, 'ogg', 'ogg'),
(4, 'Your record has been saved.', 'تم حفظ سجلك.'),
(4, 'Contact', 'اتصال'),
(4, 'Search Contact', 'البحث عن جهة الاتصال'),
(4, 'Registered', 'مسجل'),
(4, 'Message Reply', 'رد الرسالة'),
(4, 'Reply', 'رد'),
(4, 'Send reply', 'أرسل الرد'),
(4, 'Email sent successfully', 'أرسل البريد الإلكتروني بنجاح'),
(4, 'Enter your page name', 'أدخل اسم صفحتك'),
(4, 'Payment Document', 'وثيقة الدفع'),
(4, '(jpg, pdf, txt, png, docx)', '(JPG ، PDF ، TXT ، PNG ، DOCX)'),
(4, 'Pay offline', 'دفع دون اتصال'),
(4, 'Pay by Razorpay', 'دفع من قبل Razorpay'),
(4, 'pay by paystack', 'الدفع بواسطة PayStack'),
(4, 'Pay', 'يدفع'),
(4, 'Remove from cart', 'ترفع من العربة'),
(4, 'Add Newsletter', 'أضف النشرة الإخبارية');